services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-tecnico
    ports:
      - "8080:8080" # Mapea solo el puerto del backend al host
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=jdbc:postgresql://postgres-container:5432/postgres
      - DB_USER=postgres
      - DB_PASS=Carlosbeto0308*#
      - JWT_SECRET=grupoctc
      - JWT_EXPIRATION=86400000

networks:
  postgres_default:
    external: true

