services:
  gestion_zelectec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-tecnico
    ports:
      - "8080:8080"
    environment:
     SPRING_PROFILES_ACTIVE: prod
     DB_URL:jdbc: postgresql://postgres:5432/postgres
     DB_USER: postgres
     DB_PASS: Carlosbeto0308*#
     JWT_SECRET: grupoctc
     JWT_EXPIRATION: 86400000
networks:
  postgres_default:
    external: true

