services:
  gestion_zelectec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-tecnico
    ports:
      - "8080:8080"

networks:
  postgres_default:
    external: true

